* Examples from talks and papers

The Coq (Rcoq) files in this repository are morpological fragment analyses.
Some are fleshed out examples from talks or papers.
In addition, Wao2.v includes the code of the formal theory used in my thesis, "Wao Terero Lexical Suffixes".
This represents my most current work on morphological theory and the most advanced formalism.

The code may be poorly commented.
These files are intended to back up high level discussion from less technical talks and papers, demonstrating that there is no hand waving in my formal work, even if it is necessary to simplify the presentation of analyses for general audiences.
Please contact me if you have any questions about these files.
I make them available not because they are polished, but in the interest of open science.
Please contact me before citing any work found here.

** Background

Some of the explanations in these files assume a knowledge of LCG. For
a brief introduction, see the files:

- introlcgho.pdf
- raisingho.pdf

I also lean considerably on the work of Jordan Needle for a formalism of key semantic theories.

His work is found in:

- CDS_prims.v
- dynamic.v
- extensions.v
- THS.v
- Vect.v

Many of the concepts encoded in those files are described in detail in Jordan Needle's thesis, [[https://etd.ohiolink.edu/acprod/odb_etd/ws/send_file/send?accession=osu1732611563080209&disposition=inline][Relational Dynamic Categorial Grammar]].

** Potawatomi possession: PotawatomiPoss.v

The phenomenon is described in:

- [[https://noah.diewald.me/files/aimm4poster.pdf][The structure of Potawatomi hybrid-class overabundance]]

** Quechua plurals: QuechuaPlural.v

The phenomenon is described in:

- [[https://noah.diewald.me/files/diewald2018wp.pdf][WP for sign-based CGs: a focus on morphotactics]]
- [[https://noah.diewald.me/files/free_2021.pdf][Overabundance and the interface]]

** Wao Tededo future tense: WaoFuture.v

The phenomenon is described in:

- [[https://noah.diewald.me/files/free_2021.pdf][Overabundance and the interface]]

** Polysemy in Wao Terero Lexical Suffixes: Wao.v

The phenomenon is described in:

- [[https://noah.diewald.me/ismo2021.pdf][Wao Terero lexical suffixes: Bridging the lexicon and discourse]]

** Lexical Suffix Analysis for Thesis: Wao2.v

This is a substantial analysis of lexical suffixes and inflection in Wao Terero, which is described in my thesis.
I will post a link to the thesis when it is complete.
